package com.spring.ai.demo.demo.advisors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.client.ChatClientRequest;
import org.springframework.ai.chat.client.ChatClientResponse;
import org.springframework.ai.chat.client.advisor.api.CallAdvisor;
import org.springframework.ai.chat.client.advisor.api.CallAdvisorChain;
import org.springframework.ai.chat.client.advisor.api.StreamAdvisor;
import org.springframework.ai.chat.client.advisor.api.StreamAdvisorChain;
import org.springframework.stereotype.Component;
import reactor.core.publisher.Flux;



@Component
public class TokenPrintAdvisor implements CallAdvisor, StreamAdvisor {

    Logger logger= LoggerFactory.getLogger(TokenPrintAdvisor.class);

    @Override
    public ChatClientResponse adviseCall(ChatClientRequest chatClientRequest, CallAdvisorChain callAdvisorChain) {

        this.logger.info("Token Print Advisor is called");

        this.logger.info("Request : {}",chatClientRequest.prompt().getContents());

        ChatClientResponse chatClientResponse=callAdvisorChain.nextCall(chatClientRequest);

        this.logger.info("Prompt/Request Tokens : {} ",chatClientResponse
                .chatResponse()
                .getMetadata()
                .getUsage()
                .getPromptTokens());

        this.logger.info("Response received from the model");

//        this.logger.info("Response : {}",chatClientResponse.chatResponse()
//                .getResult()
//                .getOutput()
//                .getText());

        this.logger.info("Tokens consumed for processing response : {} ",chatClientResponse
                .chatResponse()
                .getMetadata()
                .getUsage()
                .getCompletionTokens());

        this.logger.info("Total tokens used : {} ",chatClientResponse
                .chatResponse()
                .getMetadata()
                .getUsage()
                .getTotalTokens());

        // prompt-token --> no.of tokens in input (user message + system message + history + function/tool/call)
        // completion-token --> no.of tokens in the output generated by model
        // total token --> prompt-token + completion-token

        return chatClientResponse;
    }

    @Override
    public Flux<ChatClientResponse> adviseStream(ChatClientRequest chatClientRequest, StreamAdvisorChain streamAdvisorChain) {
        return null;
    }

    @Override
    public String getName() {
        return this.getClass().getName();
    }

    @Override
    public int getOrder() {
        return 0;
    }
}
